### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [duckinator/quantum-experiments#1]
I recently came across your project quantum-experiments and I noticed that the repository github.com/duckinator/quantum-experiments currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by duckinator** [comment]
This was intended to be under the MIT license. I'll try to remember to do that after I sleep.

**Comment by duckinator** [comment]
@cbjuan @vabarbosa Is there a reason for the heavily-coordinated spam effort to get even the tiniest, useless repositories using qiskit to release their code under the Apache license?

I'm trying to assume you're doing this in good faith, so I'll give some feedback on the approach you've taken.

First: [I believe you are in violation of GitHub's Acceptable Use Policy, specifically the section about Spam.](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#4-spam-and-inauthentic-activity-on-github)

Second: Your initial message implies that the Apache license is somehow more open source then other licenses. Then, you railroad an Apache license in a follow-up PR from a different account, seemingly in an attempt to make it appear more authentic.

But @cbjuan, your GitHub bio claims you work at IBM! If this is true, you're giving IBM a _really_ bad reputation with this.

But I doubt you're never going to see this. @cbjuan opened over 3,000 issues, and @vabarbosa opened over 300 pull requests. Even if both accounts are real accounts, operated by different people, you probably have so many notifications you can never follow up on any of them!

All you're doing is spamming tiny repositories where people are playing with qiskit, with no follow-through and no real interaction. This isn't useful. **The shotgun approach to open source contributions is NOT welcome.**

**You are actively pushing people away from qiskit and IBM Quantum.**

**Comment by cbjuan** [comment]
Sorry if that's your impression. We're doing this in good faith.

Thanks for your feedback
